workflows:
  build-tracker:
    name: Build Tracker APK
    max_build_duration: 120
    scripts:
      - name: Install dependencies
        script: |
          python -m pip install --upgrade pip
          pip install buildozer kivy plyer
      - name: Build APK
        script: |
          buildozer android debug
